# \u914D\u7F6E\u7AEF\u53E3
server:
  port: 8090

# \u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdemo?useSSL=false
    username: root
    password: zhoudbw_tian
    driver-class-name: com.mysql.jdbc.Driver

  # JPA\u76F8\u5173\u914D\u7F6E
  jpa:
    # \u81EA\u52A8\u521B\u5EFA|\u66F4\u65B0|\u9A8C\u8BC1\u6570\u636E\u5E93\u8868\u7ED3\u6784
    hibernate:
      ddl-auto: update
    # \u8BBE\u7F6E\u6570\u636E\u5E93\u5F15\u64CE\u4E3AInnoDB
    database-platform:
    # \u6253\u5370sql\u8BED\u53E5\uFF0C\u65B9\u4FBF\u8C03\u8BD5\uFF0C\u9ED8\u8BA4\u662FFALSE
    show-sql: true